
name: bugReportSuggestion
about: Bug report suggestion form
description: Bug report suggestion form
title: "[Feature]: "
labels: ["feature", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: What is your name?
      placeholder: ex. Sertha Taweewattana
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
#   - type: textarea
#     id: what-happened
#     attributes:
#       label: What happened?
#       description: Also tell us, what did you expect to happen?
#       placeholder: Tell us what you see!
#       value: "A bug happened!"
#     validations:
#       required: true
  - type: dropdown
    id: typeOfRequest
    attributes:
      label: Type of request?
      description: Select the type of your request
      options:
        - New feature
        - Old feature
        - Other
      default: 0
    validations:
      required: false
  - type: dropdown
    id: os
    attributes: 
      label: What is the OS which you want to suggest?
      multiple: true
      options:
        - Android
        - ios
        - MacOS
  - type: textarea
    id: details
    attributes:
      label: What are the details of your suggestion?
      description: Explain what do you want
      value: Feature details!
      render: shell
#   - type: checkboxes
#     id: terms
#     attributes:
#       label: Code of Conduct
#       description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
#       options:
#         - label: I agree to follow this project's Code of Conduct
#           required: true




